parameters:
  "service-dir":
    default: "sdk/face"
  "dependencies":
    "additionalDirectories": []
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-python":
    package-dir: "face"
    package-name: "{package-dir}"
    package-mode: dataplane
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.AI.Vision.Face"
    namespace: "{package-dir}"
    clear-output-folder: true
    model-namespace: false
  "@azure-tools/typespec-ts":
    package-dir: "face-rest"
    generateMetadata: true
    generateTest: true
    packageDetails:
      name: "@azure-rest/face-rest"
      description: "Face Service"
  "@azure-tools/typespec-java":
    package-dir: "face"
    namespace: com.face
linter:
  extends:
    - "@azure-tools/typespec-azure-core/all"
